services:
  - type: web
    name: safecart-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CARRIER_TRACKING_MOCK
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_ENV
        value: "TEST"
